# SPDX-License-Identifier: GPL-3.0-or-later
"""
Linear-elastic FEA on a regular voxel grid.

8-node trilinear hexahedral elements, all identical in shape, so we build the
element stiffness matrix KE once and run a *matrix-free* conjugate-gradient
solve: K*u is evaluated element-by-element with vectorised numpy, never
assembling a global sparse matrix (keeps us scipy-free).

The solve is restricted to elements that actually exist (inside the build
space): only their nodes get DOFs, so empty margin around the part costs
nothing. All array work goes through the compute backend (``core.backend``):
the hosted edition's backend is pure numpy, while the optional GPU edition's
backend can route the same code onto a GPU array library. The maths is identical
either way.

DOF numbering (original/full space): node n has DOFs [3n, 3n+1, 3n+2].
Grid nodes: (nx+1)*(ny+1)*(nz+1) for an nx*ny*nz element grid.
"""

import numpy as np

from . import backend
from . import compute_plan


# ---------------------------------------------------------------------------
# Element stiffness matrix (unit cube, generated by Gauss quadrature)
# ---------------------------------------------------------------------------

def _hex8_KE(E=1.0, nu=0.3):
    """24x24 stiffness for a unit cube, isotropic material."""
    nodes = np.array([
        [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
        [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
    ], dtype=float)

    c = E / ((1 + nu) * (1 - 2 * nu))
    C = c * np.array([
        [1 - nu, nu, nu, 0, 0, 0],
        [nu, 1 - nu, nu, 0, 0, 0],
        [nu, nu, 1 - nu, 0, 0, 0],
        [0, 0, 0, (1 - 2 * nu) / 2, 0, 0],
        [0, 0, 0, 0, (1 - 2 * nu) / 2, 0],
        [0, 0, 0, 0, 0, (1 - 2 * nu) / 2],
    ])

    g = 1.0 / np.sqrt(3.0)
    gp = [-g, g]
    KE = np.zeros((24, 24))
    for xi in gp:
        for eta in gp:
            for zeta in gp:
                dN = np.zeros((3, 8))
                for i, (a, b, c_) in enumerate(nodes):
                    dN[0, i] = a * (1 + b * eta) * (1 + c_ * zeta) / 8.0
                    dN[1, i] = b * (1 + a * xi) * (1 + c_ * zeta) / 8.0
                    dN[2, i] = c_ * (1 + a * xi) * (1 + b * eta) / 8.0
                J = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 0.5]])
                detJ = np.linalg.det(J)
                dNxyz = np.linalg.solve(J, dN)
                B = np.zeros((6, 24))
                for i in range(8):
                    bx, by, bz = dNxyz[:, i]
                    c0 = 3 * i
                    B[0, c0] = bx
                    B[1, c0 + 1] = by
                    B[2, c0 + 2] = bz
                    B[3, c0] = by
                    B[3, c0 + 1] = bx
                    B[4, c0 + 1] = bz
                    B[4, c0 + 2] = by
                    B[5, c0] = bz
                    B[5, c0 + 2] = bx
                KE += (B.T @ C @ B) * detJ
    return KE


def _hex8_B_C(nu=0.3):
    """B (strain-displacement, 6x24) evaluated at the cell centroid, plus the
    unit-E material matrix C (6x6). Row/col order is [xx, yy, zz, xy, yz, zx],
    matching ``_hex8_KE``. A single centroid sample (rather than 8 Gauss
    points) gives one representative stress per element, which is standard
    hex8 stress recovery and all a per-voxel heatmap needs.
    """
    nodes = np.array([
        [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
        [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
    ], dtype=float)

    c = 1.0 / ((1 + nu) * (1 - 2 * nu))
    C = c * np.array([
        [1 - nu, nu, nu, 0, 0, 0],
        [nu, 1 - nu, nu, 0, 0, 0],
        [nu, nu, 1 - nu, 0, 0, 0],
        [0, 0, 0, (1 - 2 * nu) / 2, 0, 0],
        [0, 0, 0, 0, (1 - 2 * nu) / 2, 0],
        [0, 0, 0, 0, 0, (1 - 2 * nu) / 2],
    ])

    xi = eta = zeta = 0.0
    dN = np.zeros((3, 8))
    for i, (a, b, c_) in enumerate(nodes):
        dN[0, i] = a * (1 + b * eta) * (1 + c_ * zeta) / 8.0
        dN[1, i] = b * (1 + a * xi) * (1 + c_ * zeta) / 8.0
        dN[2, i] = c_ * (1 + a * xi) * (1 + b * eta) / 8.0
    J = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 0.5]])
    dNxyz = np.linalg.solve(J, dN)
    B = np.zeros((6, 24))
    for i in range(8):
        bx, by, bz = dNxyz[:, i]
        c0 = 3 * i
        B[0, c0] = bx
        B[1, c0 + 1] = by
        B[2, c0 + 2] = bz
        B[3, c0] = by
        B[3, c0 + 1] = bx
        B[4, c0 + 1] = bz
        B[4, c0 + 2] = by
        B[5, c0] = bz
        B[5, c0 + 2] = bx
    return B, C


# ---------------------------------------------------------------------------
# Element <-> global DOF connectivity
# ---------------------------------------------------------------------------

def _node_id(ix, iy, iz, nx, ny):
    return ix + (nx + 1) * (iy + (ny + 1) * iz)


def build_edof(nx, ny, nz):
    """Return edofMat [nelem, 24] of global DOF indices per element."""
    ex, ey, ez = np.meshgrid(
        np.arange(nx), np.arange(ny), np.arange(nz), indexing='ij')
    ex = ex.ravel()
    ey = ey.ravel()
    ez = ez.ravel()
    offs = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
            (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]
    edof = np.empty((ex.size, 24), dtype=np.int64)
    for k, (ox, oy, oz) in enumerate(offs):
        nid = _node_id(ex + ox, ey + oy, ez + oz, nx, ny)
        edof[:, 3 * k] = 3 * nid
        edof[:, 3 * k + 1] = 3 * nid + 1
        edof[:, 3 * k + 2] = 3 * nid + 2
    return edof


# ---------------------------------------------------------------------------
# Connectivity: drop voxel islands that cannot reach any support.
#
# A voxel (or small cluster) connected to the active region only by a
# face/edge/corner, with no chain of active neighbours back to a fixed
# (bearing) node, is a zero-energy rigid-body mode: nothing resists it
# moving freely, so K is singular even though the main body is well-posed.
# Removing such islands from the active set before solving fixes this at the
# root rather than just failing to converge. Pure numpy (no
# scipy.ndimage.label, see module docstring). Flood fill is iterative
# 6-connected dilation from every element touching a fixed node, which
# converges in O(grid diameter) passes, each O(nelem) vectorised numpy.
# ---------------------------------------------------------------------------

def seed_from_fixed_dofs(nx, ny, nz, fixed_dofs):
    """Bool (nx,ny,nz) mask of elements touching at least one fixed node."""
    n_nodes = (nx + 1) * (ny + 1) * (nz + 1)
    fixed_dofs = np.asarray(fixed_dofs, dtype=np.int64)
    if fixed_dofs.size == 0:
        return np.zeros((nx, ny, nz), dtype=bool)
    fixed_nodes = np.unique(fixed_dofs // 3)
    is_fixed_node = np.zeros(n_nodes, dtype=bool)
    is_fixed_node[fixed_nodes] = True
    edof_full = build_edof(nx, ny, nz)
    node_ids = edof_full[:, 0::3] // 3          # (nelem, 8)
    seed = is_fixed_node[node_ids].any(axis=1)
    return seed.reshape(nx, ny, nz)


def connected_component_mask(active3d, seed3d):
    """6-connected flood fill of ``active3d`` starting from ``seed3d``.

    Returns a bool array of the same shape: every active element reachable
    from a seed element through a chain of face-adjacent active elements.
    If seed3d has no overlap with active3d, returns an all-False mask (the
    caller decides what that means -- e.g. "no support reaches the part at
    all", already reported separately as its own error).
    """
    active3d = np.asarray(active3d, dtype=bool)
    reached = np.asarray(seed3d, dtype=bool) & active3d
    if not reached.any():
        return reached
    while True:
        grown = reached.copy()
        grown[1:, :, :] |= reached[:-1, :, :]
        grown[:-1, :, :] |= reached[1:, :, :]
        grown[:, 1:, :] |= reached[:, :-1, :]
        grown[:, :-1, :] |= reached[:, 1:, :]
        grown[:, :, 1:] |= reached[:, :, :-1]
        grown[:, :, :-1] |= reached[:, :, 1:]
        grown &= active3d
        if np.array_equal(grown, reached):
            return reached
        reached = grown


def drop_unsupported_islands(active3d, fixed_dofs):
    """Restrict active3d to the component(s) connected to a support.

    Returns ``(kept3d, n_removed)``. n_removed is the element count of
    everything dropped (isolated islands with no load-bearing path) -- the
    caller surfaces this as a short, non-blocking status note rather than a
    popup, since it is handled automatically, not something the user needs
    to act on.
    """
    active3d = np.asarray(active3d, dtype=bool)
    nx, ny, nz = active3d.shape
    seed3d = seed_from_fixed_dofs(nx, ny, nz, fixed_dofs)
    kept = connected_component_mask(active3d, seed3d)
    if not kept.any():
        # No active element reaches a support at all -- leave active3d
        # untouched so the existing "no supports reach any grid node" error
        # (checked by the caller) still fires with its own clear message,
        # rather than silently returning an empty part here.
        return active3d, 0
    n_removed = int(active3d.sum() - kept.sum())
    return kept, n_removed


# ---------------------------------------------------------------------------
# Matrix-free solver (restricted to active elements)
# ---------------------------------------------------------------------------

class VoxelFEA:
    """Solves K(rho) u = f matrix-free over the active (build-space) elements.

    active_elems : optional bool mask (nelem,). Only these elements - and the
    nodes they touch - enter the linear system, so empty space around the part
    is skipped entirely. The public API still speaks the full DOF space:
    solve() returns a full-length u and element_strain_energy() returns a full
    per-element array (zeros outside the active region).
    """

    def __init__(self, nx, ny, nz, nu=0.3, e_min=1e-9, active_elems=None,
                 compute_mode="AUTO", cpu_threads=0, verbose=False,
                 use_multigrid=True):
        self.nx, self.ny, self.nz = nx, ny, nz
        self.nelem = nx * ny * nz
        self.ndof_full = 3 * (nx + 1) * (ny + 1) * (nz + 1)
        self.e_min = e_min
        self.nu = nu
        # Passed straight through to multigrid.MGSolver if/when it gets
        # built (see solve()) -- kept here rather than re-derived so the MG
        # path picks its own compute plan for the FULL grid's DOF count with
        # the exact same mode/thread request the caller gave this instance,
        # not a guess.
        self._compute_mode = compute_mode
        self._cpu_threads = cpu_threads
        self.use_multigrid = use_multigrid
        self._mg = None                 # lazily built in solve(), see there
        self._fixed_dofs_full = np.zeros(0, dtype=np.int64)
        self.KE = _hex8_KE(E=1.0, nu=nu)
        self._B0, self._C0 = _hex8_B_C(nu=nu)           # centroid stress recovery
        self.edof_full = build_edof(nx, ny, nz)        # full, original DOFs

        if active_elems is None:
            self.active_elems = np.ones(self.nelem, dtype=bool)
        else:
            self.active_elems = np.asarray(active_elems, dtype=bool).ravel()

        # Compress to the DOFs actually used by active elements.
        edof_a = self.edof_full[self.active_elems]      # (na, 24) original DOFs
        used = np.unique(edof_a)
        remap = -np.ones(self.ndof_full, dtype=np.int64)
        remap[used] = np.arange(used.size)
        self.used_dofs = used
        self.remap = remap
        self.ndof = int(used.size)                       # reduced size
        self.edof = remap[edof_a]                        # (na, 24) reduced DOFs

        self.free = None
        self._diag = None
        self.verbose = verbose
        self.last_iters = 0
        self.last_converged = None
        self.last_resid_ratio = float("nan")
        self.resid_history = []

        # Decide CPU / single-GPU / multi-GPU / multi-process-CPU for this
        # grid's actual (reduced) DOF count -- see core/compute_plan.py for
        # the thresholds. When the plan is "parallel" (multi_gpu/multi_cpu),
        # the hot gather-matmul-scatter in _apply_K/_diagonal is delegated to
        # a pool and the surrounding CG vector ops stay on host numpy (O(ndof),
        # cheap, and the pool already hands back host arrays). Every matvec
        # here goes through the pool when one is active, unlike
        # core/multigrid.py's MGSolver whose V-cycle smoother/_restrict/
        # _prolongate deliberately bypass the pool (see MGSolver.__init__).
        self.plan = compute_plan.choose(self.ndof, mode=compute_mode,
                                        cpu_threads=cpu_threads,
                                        verbose=verbose)
        self._pool = None
        self.xp = np if self.plan.parallel else self.plan.xp
        self._init_pool()
        self.KE_x = self.xp.asarray(self.KE)
        self.edof_x = self.xp.asarray(self.edof)

    def _init_pool(self):
        """Build the multi-worker matvec pool if the plan calls for one,
        falling back one rung (multi_gpu -> gpu -> cpu, multi_cpu -> cpu) if
        it fails to construct for any reason -- a failed accelerator must
        never abort the solve, only make it slower."""
        plan = self.plan
        if plan.kind == "multi_cpu":
            from . import parallel_cpu
            try:
                self._pool = parallel_cpu.CPUMatVecPool(
                    self.edof, self.KE, self.ndof, plan.n_workers,
                    verbose=self.verbose)
                return
            except Exception as exc:
                if self.verbose:
                    print(f"[BlenderFEA] multi-CPU pool unavailable ({exc}); "
                          f"falling back to single-process CPU")
                self.plan = compute_plan.ComputePlan(
                    "cpu", np, 1, "CPU (multi-CPU fallback)")
                self.xp = np
        elif plan.kind == "multi_gpu":
            from . import parallel_gpu
            try:
                self._pool = parallel_gpu.GPUMatVecPool(
                    self.edof, self.KE, self.ndof, plan.n_workers,
                    verbose=self.verbose)
                return
            except Exception as exc:
                if self.verbose:
                    print(f"[BlenderFEA] multi-GPU pool unavailable ({exc}); "
                          f"falling back to single GPU/CPU")
                self.plan = compute_plan.choose(
                    self.ndof, mode="GPU", verbose=self.verbose)
                self.xp = self.plan.xp

    def close(self):
        """Release the matvec pool's workers/devices, if any were started."""
        if self._pool is not None:
            try:
                self._pool.close()
            except Exception:
                pass
            self._pool = None
        if self._mg is not None:
            try:
                self._mg.close()
            except Exception:
                pass
            self._mg = None

    def set_fixed(self, fixed_dofs):
        """fixed_dofs: original global DOF indices to constrain."""
        fixed_dofs = np.asarray(fixed_dofs, dtype=np.int64)
        # Kept in ORIGINAL (uncompressed) numbering too -- multigrid.MGSolver
        # works on the full regular grid, not this class's active-element-
        # compressed DOF space, so it needs the un-remapped indices (see
        # solve()'s multigrid path below).
        self._fixed_dofs_full = fixed_dofs
        free = np.ones(self.ndof, dtype=bool)
        fd = self.remap[fixed_dofs]
        fd = fd[fd >= 0]
        free[fd] = False
        self.free = free

    def _Evec_active(self, Evec_full):
        return np.asarray(Evec_full, dtype=float)[self.active_elems]

    def _apply_K(self, u, Evec_a):
        # BLAS matmul (KE is symmetric) then a bincount scatter-add. The numpy
        # and GPU array modules share these semantics, so one path runs on both.
        # When a multi-CPU/multi-GPU pool is active this whole gather-matmul-
        # scatter is delegated to it instead (see core/parallel_cpu(_gpu).py).
        if self._pool is not None:
            return backend.asnumpy(self.xp.asarray(
                self._pool.apply(backend.asnumpy(u))))
        xp = self.xp
        ue = u[self.edof_x]                                  # (na, 24)
        ke_ue = (ue @ self.KE_x.T) * Evec_a[:, None]
        return xp.bincount(self.edof_x.ravel(),
                           weights=ke_ue.ravel(), minlength=self.ndof)

    def _diagonal(self, Evec_a):
        xp = self.xp
        if self._pool is not None:
            d = self.xp.asarray(self._pool.diagonal())
        else:
            diagKE = xp.diag(self.KE_x)
            contrib = Evec_a[:, None] * diagKE[None, :]          # (na, 24)
            d = xp.bincount(self.edof_x.ravel(),
                            weights=contrib.ravel(), minlength=self.ndof)
        d = xp.where(d == 0, 1.0, d)
        return d

    def solve(self, Evec, f, tol=1e-4, max_cg=None, x0=None,
             progress_cb=None):
        """Preconditioned CG. Returns full-length u (numpy).

        Dispatches to a geometric-multigrid V-cycle preconditioner
        (core.multigrid.MGSolver, ``use_multigrid=True`` by default) instead
        of this class's original plain Jacobi (diagonal) preconditioning,
        whose iteration count grows with grid size. MGSolver works on the
        full regular grid rather than this class's active-element-compressed
        DOF space, with inactive elements carrying e_min stiffness instead
        of being dropped from the system. Construction/solve failures
        (including a stall/divergence guard inside MGSolver.solve() itself,
        see multigrid.py) fall back to plain Jacobi-PCG below rather than
        aborting the solve, always printed (not gated on verbose).

        x0 : optional warm-start (full-length numpy) -- cuts CG iterations
        when the structure changes only slightly between calls.

        progress_cb : optional ``callback(iteration, resid_ratio, tol)``,
        invoked after every CG iteration, for a caller that wants to
        stream/plot convergence (e.g. core/solve_worker.py writing it to
        status.json). solve() itself does no throttling.

        self.resid_history collects every iteration's resid_ratio so a
        caller can render a full convergence plot after the fact even
        without hooking progress_cb.
        """
        if self.free is None:
            raise RuntimeError("call set_fixed() before solve()")
        if self.use_multigrid:
            u_full = self._solve_multigrid(Evec, f, tol=tol, max_cg=max_cg,
                                           x0=x0, progress_cb=progress_cb)
            if u_full is not None:
                return u_full
            # _solve_multigrid already printed why it's falling back.
        return self._solve_jacobi(Evec, f, tol=tol, max_cg=max_cg, x0=x0,
                                  progress_cb=progress_cb)

    def _solve_multigrid(self, Evec, f, tol, max_cg, x0, progress_cb):
        """Try the MG-preconditioned solve; return None (never raise) if it
        can't be used, so solve() can fall back to plain Jacobi-PCG."""
        if self._mg is None:
            try:
                from .multigrid import MGSolver
                self._mg = MGSolver(
                    self.nx, self.ny, self.nz, self._fixed_dofs_full,
                    nu=self.nu, compute_mode=self._compute_mode,
                    cpu_threads=self._cpu_threads, verbose=self.verbose)
            except Exception as exc:
                import traceback
                print(f"[BlenderFEA] MGSolver construction failed for "
                      f"{self.nx}x{self.ny}x{self.nz} "
                      f"(mode={self._compute_mode}): {exc}\n"
                      f"{traceback.format_exc()}"
                      f"[BlenderFEA] Falling back to plain Jacobi-PCG (no "
                      f"multigrid preconditioning) for this solve.")
                self.use_multigrid = False
                self._mg = None
                return None

        # Full-grid density: e_min stiffness where this instance's active
        # mask is False, same SIMP-style void convention multigrid.py's own
        # docstring documents ("void elements carry e_min stiffness"). Evec
        # here is already the caller's full-length (nelem) per-element
        # stiffness scale (see core/solve_worker.py), never pre-restricted
        # to active elements the way _Evec_active() restricts it for the
        # Jacobi path below.
        Evec_full = np.asarray(Evec, dtype=float)
        Evec_mg = np.where(self.active_elems, Evec_full,
                           Evec_full * self.e_min)
        f_full = np.asarray(f, dtype=float)
        max_cg_mg = max_cg  # MGSolver defaults this to 1000 when None
        try:
            u_full = self._mg.solve(Evec_mg, f_full, tol=tol,
                                    max_cg=max_cg_mg, x0=x0,
                                    progress_cb=progress_cb)
        except Exception as exc:
            import traceback
            print(f"[BlenderFEA] MGSolver.solve() failed for "
                  f"{self.nx}x{self.ny}x{self.nz}: {exc}\n"
                  f"{traceback.format_exc()}"
                  f"[BlenderFEA] Falling back to plain Jacobi-PCG (no "
                  f"multigrid preconditioning) for this solve.")
            self.use_multigrid = False
            try:
                self._mg.close()
            except Exception:
                pass
            self._mg = None
            return None

        self.last_iters = self._mg.last_iters
        self.last_converged = self._mg.last_converged
        self.last_resid_ratio = self._mg.last_resid_ratio
        self.resid_history = list(self._mg.resid_history)
        return u_full

    def _solve_jacobi(self, Evec, f, tol=1e-4, max_cg=None, x0=None,
                      progress_cb=None):
        """Original plain Jacobi-(diagonal-)preconditioned CG, restricted to
        active DOFs. Used directly when ``use_multigrid=False``, and as the
        automatic fallback if MGSolver can't be built/doesn't converge (see
        solve() above).

        Convergence guards/diagnostics mirror multigrid.MGSolver.solve()
        exactly (last_iters/last_converged/last_resid_ratio, zero-denominator
        guards, an unconditional non-convergence warning): this path used to
        have none of that, so silently under-converging here - which feeds
        directly into every downstream compliance/sensitivity/stress number -
        was invisible. It's a correctness signal, not a progress log line, so
        the warning prints regardless of the verbose setting, same as MG's.
        """
        if self.free is None:
            raise RuntimeError("call set_fixed() before solve()")
        xp = self.xp
        free = xp.asarray(self.free)
        Evec_a = xp.asarray(self._Evec_active(Evec))
        if self._pool is not None:
            self._pool.set_density(backend.asnumpy(Evec_a))
        f_r = xp.asarray(np.asarray(f, dtype=float)[self.used_dofs])

        self._diag = self._diagonal(Evec_a)
        Minv = 1.0 / self._diag

        self.last_iters = 0
        self.last_converged = False
        self.last_resid_ratio = float("nan")
        self.resid_history = []

        if x0 is None:
            u = xp.zeros(self.ndof)
            r = f_r.copy()
        else:
            u = xp.asarray(np.asarray(x0, dtype=float)[self.used_dofs])
            u = xp.where(free, u, 0.0)
            r = f_r - self._apply_K(u, Evec_a)
        r = xp.where(free, r, 0.0)

        z = xp.where(free, Minv * r, 0.0)
        p = z.copy()
        rz = float(r @ z)

        fnorm = float(xp.linalg.norm(xp.where(free, f_r, 0.0)))
        if fnorm == 0:
            self.last_converged = True
            return np.zeros(self.ndof_full)
        max_cg = max_cg or 4 * int(self.free.sum())

        for it in range(max_cg):
            Kp = self._apply_K(p, Evec_a)
            Kp = xp.where(free, Kp, 0.0)
            pKp = float(p @ Kp)
            if pKp == 0.0:
                # Vanishing denominator on a well-posed SPD system: nothing
                # left to improve along p - (numerical) convergence, not an
                # error. Same reasoning/guard as MGSolver.solve().
                self.last_converged = (self.last_resid_ratio < tol)
                break
            alpha = rz / pKp
            u = u + alpha * p
            r = r - alpha * Kp
            self.last_iters = it + 1
            self.last_resid_ratio = (
                float(xp.linalg.norm(xp.where(free, r, 0.0))) / fnorm)
            self.resid_history.append(self.last_resid_ratio)
            if progress_cb is not None:
                progress_cb(self.last_iters, self.last_resid_ratio, tol)
            if self.last_resid_ratio < tol:
                self.last_converged = True
                break
            z = xp.where(free, Minv * r, 0.0)
            rz_new = float(r @ z)
            if rz == 0.0:
                # Same reasoning: the preconditioner has nothing left to
                # contribute - restart the search direction instead of
                # dividing by zero (a valid PCG restart).
                p = z.copy()
            else:
                p = z + (rz_new / rz) * p
            p = xp.where(free, p, 0.0)
            rz = rz_new

        if not self.last_converged:
            print(f"[BlenderFEA] WARNING: CG did not converge in {max_cg} "
                  f"iterations (tol={tol:g}, final residual ratio="
                  f"{self.last_resid_ratio:.3e}). Returned displacement may "
                  f"be inaccurate - if this keeps appearing, it explains "
                  f"visible stress/shape artefacts; if it never appears, "
                  f"under-convergence can be ruled out as the cause.")

        u = xp.where(free, u, 0.0)
        u_full = np.zeros(self.ndof_full)
        u_full[self.used_dofs] = backend.asnumpy(u)
        return u_full

    def element_strain_energy(self, u_full):
        """Per-element u_e^T KE u_e for ALL elements (numpy, length nelem)."""
        u = np.asarray(u_full)
        ce = np.zeros(self.nelem)
        ue = u[self.edof_full[self.active_elems]]
        ke_ue = ue @ self.KE.T
        ce[self.active_elems] = np.einsum('ei,ei->e', ue, ke_ue)
        return ce

    def element_von_mises_stress(self, u_full, Evec):
        """Per-element von Mises stress for ALL elements (numpy, length nelem).

        Single-point (centroid) stress recovery, scaled by each element's
        actual Young's modulus. Zero outside the active region. Cheap --
        same cost class as element_strain_energy.
        """
        u = np.asarray(u_full)
        vm = np.zeros(self.nelem)
        if not np.any(self.active_elems):
            return vm
        ue = u[self.edof_full[self.active_elems]]            # (na, 24)
        strain = ue @ self._B0.T                              # (na, 6)
        stress0 = strain @ self._C0.T                         # (na, 6), E=1
        Evec_a = np.asarray(Evec, dtype=float)[self.active_elems]
        stress = stress0 * Evec_a[:, None]
        sx, sy, sz = stress[:, 0], stress[:, 1], stress[:, 2]
        txy, tyz, tzx = stress[:, 3], stress[:, 4], stress[:, 5]
        vm_a = np.sqrt(np.maximum(
            0.5 * ((sx - sy) ** 2 + (sy - sz) ** 2 + (sz - sx) ** 2)
            + 3.0 * (txy ** 2 + tyz ** 2 + tzx ** 2), 0.0))
        vm[self.active_elems] = vm_a
        return vm
